#!/bin/sh
# Shitty script to aid with parsing conflicts in order to perform slot rebuilds independent of @world
# Example usage (calculate upgrade for qtcore and all its revdeps):
# echo "dev-qt/qtcore:5" > /tmp/pkg.txt
# emerge -pu --usepkg=n --verbose-conflicts $(cat /tmp/pkg.txt) 2>&1 | tee /dev/stderr | /etc/portage/scripts/filter-required /tmp/pkg.txt
# ... repeat last line a number of times until it resolves,
#     then run "emerge -1u $(cat /tmp/pkg.txt)"
#     Play with removing/adding the -u flag if facing problems.
tmp="$(mktemp)"
grep ' =\|=[ \[]\|:[^ ]\+/' | sed -n -e 's/^.* required by (\([^,]\+\), installed).*$/\1/p' | sed \
    -e 's/::[^:]*$//' \
    -e 's/\/[0-9\.]\+$//' \
    -e 's/-[0-9]\+:/:/' \
    -e 's/-r[0-9]\+:/:/' \
    -e 's/_p[0-9]\+:/:/' \
    -e 's/-[0-9\.]\+:/:/' \
    | cat - "$1" | sort | uniq > "$tmp"
diff "$1" "$tmp"
cat "$tmp" > "$1"
rm "$tmp"
