#!/bin/sh
# Installing: symlink to /etc/cron.hourly/updates
set -e

dir=/var/spool/updates
mkdir -p "$dir"

# Flags
force=false
nobinpkg=false
while test -n "$1"; do
    if [ "$1" = '-f' ]; then
        force=true
    fi
    if [ "$1" = '-n' ]; then
        nobinpkg=true
    fi
    shift
done

# Check whether it was run successfully already
prevsync=
if test -r "$dir/timestamp"; then
    prevsync=`cat "$dir/timestamp"`
fi
cursync=`date +%Y%m`
day=`date +%d`

# Do not run it when on battery power
online=1
for psupply in AC ADP{0..9} ; do
    sysfile="/sys/class/power_supply/$psupply/online"

    if [ -f $sysfile ] ; then
        if [ `cat $sysfile 2>/dev/null`x = 1x ]; then
            online=1
            break
        else
            online=0
        fi
    fi
done
if ! $force && [ $online = 0 ]; then
    exit 0
fi

# Generate upgrade stats
update() {
    rm -f "$dir/pending-tree"
    opts=
    $nobinpkg && opts='--usepkg=n'
    { emerge -puDU --package-moves=n --binpkg-changed-deps=y --color=y $opts @world 2>&1 || return; } | tee "$dir/pending"
    emerge -puDU --package-moves=n --binpkg-changed-deps=y --color=y --tree $opts @world 2>&1 | tee "$dir/pending-tree"
}

# Force update
if $force; then
    rm -f "$dir/pending"
fi

# If already ran, check if pending needs updating
if [ "$cursync" = "$prevsync" -o "$day" -le 1 ]; then
    if [ ! -f "$dir/pending" -o /var/log/emerge.log -nt "$dir/pending" ]; then
        update
    fi
    exit 0
fi

# Try to sync
emerge --ask=n --package-moves=n --sync | tee "$dir/sync.log"
update

# If successful, write it out
echo "$cursync" > "$dir/timestamp"
